name: yumly_ever_after
description: "recipe-app task"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  dartz: ^0.10.1
  equatable: ^2.0.7

  # validation
  formz: ^0.8.0

  # ui
  shimmer: ^3.0.0
  fluttertoast: ^8.2.8

  # dependency injection
  get_it: ^8.0.2

  # state management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

  # local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # media
  cached_network_image: ^3.4.1

  # network
  dio: ^5.7.0
  connectivity_plus: ^6.1.0

  # native APIs
  path_provider: ^2.1.5

dev_dependencies:
  # code analysis
  flutter_lints: ^5.0.0

  # code generators
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
